Feature/image detail
GetStream/stream-chat-flutter pull request #143
Opened 2020-11-19 15:33 UTC by deven98

Implemented Image detail screen

2020-11-23 14:20 UTC, xsahil03x requested changes
I have mentioned some of my findings, Rest LGTM.

2020-11-23 14:20 UTC, xsahil03x commented on lib/src/image_actions_modal.dart
> +      tileColor: Colors.white,
Splash is not visible due to the white tile color, Maybe remove this line.

2020-11-23 15:29 UTC, imtoori commented on lib/src/image_actions_modal.dart
> +                              urls[currentIndex].split('?')[0]);
it doesn't fail on ios, but it's slow
we could add a loading indicator

2020-11-23 15:30 UTC, imtoori commented
@deven98  I think we should handle videos as well

2020-11-24 09:12 UTC, xsahil03x commented on lib/src/image_actions_modal.dart
> +                              urls[currentIndex].split('?')[0]);
Looks like it was some emulator bug, but there is still one error. Most of the image paths don't have a valid image extension.

eg : https://picsum.photos/seed/53/200/200

so this throws an exception

```dart[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Invalid argument(s): File on path is not an image.
E/flutter (28315): #0      GallerySaver.saveImage (package:gallery_saver/gallery_saver.dart:50:7)
E/flutter (28315): #1      ImageActionsModal._buildPage.<anonymous closure> (package:stream_chat_flutter/src/image_actions_modal.dart:121:46)
E/flutter (28315): #2      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
E/flutter (28315): #3      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
E/flutter (28315): #4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
E/flutter (28315): #5      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
E/flutter (28315): #6      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
E/flutter (28315): #7      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:259:7)
E/flutter (28315): #8      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
E/flutter (28315): #9      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:362:20)
E/flutter (28315): #10     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
E/flutter (28315): #11     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
E/flutter (28315): #12     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
E/flutter (28315): #13     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
E/flutter (28315): #14     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
E/flutter (28315): #15     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (28315): #16     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (28315): #17     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (28315): #18     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter (28315): #19     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
```

2020-11-24 09:13 UTC, deven98 commented on lib/src/image_actions_modal.dart
> +                              urls[currentIndex].split('?')[0]);
This is going to be problematic, I'll see what I can do

2020-12-02 15:50 UTC, merged