[ISSUE-1432] Fixing watchers stream
GetStream/stream-chat-flutter pull request #1448
Opened 2023-01-30 16:59 UTC by leandroBorgesFerreira

# Submit a pull request

## CLA

- [ ] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required).
- [ ] The code changes follow best practices
- [ ] Code changes are tested (add some information if not applicable)

## Description of the pull request

2023-01-31 11:21 UTC, xsahil03x commented on packages/stream_chat/lib/src/client/channel.dart
> +      channelState.watchers!.add(user);
we should not update the `channelState` properties directly, rather just emit a new state with the update `channelState`.

```dart
updateChannelState(
    channelState.copyWith(
        watchers: updatedWatcher
    )
);
```

2023-01-31 11:22 UTC, xsahil03x commented on packages/stream_chat/lib/src/client/channel.dart
> +          channelState.watchers?.remove(event.user);
Similar thing here

2023-01-31 11:24 UTC, xsahil03x requested changes
Left some comments, you can also follow the logic we have for members.

```dart
void _listenMemberAdded() {
    _subscriptions.add(_channel.on(EventType.memberAdded).listen((Event e) {
      final member = e.member;
      final existingMembers = channelState.members ?? [];
      updateChannelState(channelState.copyWith(
        members: [
          ...existingMembers,
          member!,
        ],
      ));
    }));
  }
  
void _listenMemberRemoved() {
    _subscriptions.add(_channel.on(EventType.memberRemoved).listen((Event e) {
      final user = e.user;
      final existingMembers = channelState.members ?? [];
      updateChannelState(channelState.copyWith(
        members: existingMembers
            .where((m) => m.userId != user!.id)
            .toList(growable: false),
      ));
    }));
  }
```

2023-01-31 13:22 UTC, leandroBorgesFerreira commented on packages/stream_chat/lib/src/client/channel.dart
> +  }
Indeed, sorry I forgot this one.

2023-02-09 10:18 UTC, xsahil03x approved these changes

2023-02-09 10:18 UTC, merged