feat : ChannelListHeader
GetStream/stream-chat-flutter pull request #146
Opened 2020-11-23 12:24 UTC by xsahil03x

# Submit a pull request

## CLA

- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required).
- [x] The code changes follow best practices
- [x] Code changes are tested (add some information if not applicable)

2020-11-23 15:43 UTC, imtoori commented on lib/src/channel_list_header.dart
> +        child: UserAvatar(
I'd add 
```      
showOnlineStatus: false,
```

2020-11-23 15:44 UTC, imtoori commented on lib/src/channel_list_header.dart
> +                  StreamIcons.pen_write,
this icon is wrong
if you don't find it download it from figma

2020-11-23 15:44 UTC, imtoori requested changes
added two comments

2020-11-24 07:15 UTC, xsahil03x commented on lib/src/channel_list_header.dart
> +        child: UserAvatar(
Done 👍

2020-11-24 10:29 UTC, merged