Make public hintText field of the InputDecoration of message_input
GetStream/stream-chat-flutter pull request #170
Opened 2020-12-08 09:27 UTC by TramPamPam

# Submit a pull request

## CLA

- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required).
- [x] The code changes follow best practices
- [x] Code changes are tested (add some information if not applicable)

## Description of the pull request

2020-12-08 09:33 UTC, TramPamPam commented
@imtoori @xsahil03x @tbarbugli

Could someone review this pull request, please?

2020-12-08 10:29 UTC, imtoori requested changes
I added a comment
Also, we could move it to the theme. I think it would be better because the MessageInput is also used while editing a message and to customise it you should set `editMessageInputBuilder` and that's not so nice.

2020-12-08 10:29 UTC, imtoori commented on lib/src/message_input.dart
> +  final String hintText = 'Write a message';
I think we should add this property in the widget constructor

2020-12-08 11:08 UTC, TramPamPam commented
@imtoori I've added this property to widget constructor. Concerning theme - I'm not sure where to add this field.

2020-12-08 14:19 UTC, TramPamPam commented
@imtoori any update on this?

2020-12-08 15:46 UTC, imtoori commented
Hey @TramPamPam I'll add it in the theme and I'll ping you once it's done

2020-12-09 13:58 UTC, imtoori commented
Closing this in favour of #172 
@TramPamPam let me know what do you think about it

2020-12-09 13:58 UTC, closed without merging

2020-12-09 14:00 UTC, TramPamPam commented
@imtoori 
That should do. Thanks!