feat: Added tests
GetStream/stream-chat-flutter pull request #335
Opened 2021-03-16 13:19 UTC by deven98

Added UI tests

2021-03-25 09:36 UTC, imtoori commented
@ROCKSTARfromday1 take a look at our website to get to know how you can use our service for your purposes :) https://getstream.io/

2021-04-08 13:39 UTC, Nash0x7E2 requested changes
Consider using setup and teardown for defining mocks

2021-04-08 13:39 UTC, Nash0x7E2 commented on packages/stream_chat_flutter/lib/src/attachment_actions_modal.dart
>                            Navigator.pop(context);
You can cascade these methods :)

2021-04-08 13:39 UTC, Nash0x7E2 commented on packages/stream_chat_flutter/test/src/attachment_widgets_test.dart
> +  // testWidgets(
Consider removing unused code :)

2021-04-08 13:39 UTC, Nash0x7E2 commented on packages/stream_chat_flutter/test/src/channel_header_test.dart
> +    'shoBackButton: false should hide the StreamBackButton and '
Typo

2021-04-08 13:39 UTC, Nash0x7E2 commented on packages/stream_chat_flutter/test/src/message_text_test.dart
> +      // TODO: Add better test
How goes this?

2021-04-08 15:43 UTC, merged