Fix/message input
GetStream/stream-chat-flutter pull request #382
Opened 2021-04-02 14:49 UTC by deven98

added issue fixes

2021-04-02 14:59 UTC, xsahil03x commented
@deven98 Let me share what @imtoori had in his mind about the builder

```dart
typedef MentionTileBuilder = Widget Function(BuildContext context, User user);

class MessageInput extends StatelessWidget {

  final MentionTileBuilder mentionTileBuilder;

  @override
  Widget build(BuildContext context) {
    return Container(
      child: mentionTileBuilder(user) ?? DefaultMentionTile(user: user),
    );
  }
}
```

```dart
class DefaultMentionTile extends StatelessWidget {
  final User user;
  final String title;
  final String subtitle;
  final Widget leading;
  final Widget trailing;
  
  @override
  Widget build(BuildContext context) {
    return ListTile(
      leading: leading ?? DefaultLeading(),
      trailing: trailing ?? DefaultTrailing(),
      title: title ?? DefaultTitle(),
      subtitle: subtitle ?? DefaultSubtitle(),
    );
  }
}
```

Then we can either return our own custom widget or do something like this.
```dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MessageInput(
      mentionTileBuilder: (user) => DefaultMentionTile(
        user : user,
        subtitle: 'myCustomSubtitle',
      ),
    )
  }
}
```

2021-04-06 05:16 UTC, xsahil03x commented
LGTM, just can we change the name from `DefaultMentionTile` to something `Stream Chat` specific as it will be easier to identify and use?

2021-04-06 07:50 UTC, imtoori requested changes
A couple of trailing commas are missing
I'd change the name from `DefaultMentionTile` to just `MentionTile`, what do you think? (cc @xsahil03x)
Otherwise LGTM

2021-04-06 07:50 UTC, imtoori commented on packages/stream_chat_flutter/lib/src/default_mention_tile.dart
> +      {this.title, this.subtitle, this.leading, this.trailing});
missing trailing comma

2021-04-06 07:50 UTC, imtoori commented on packages/stream_chat_flutter/lib/src/default_mention_tile.dart
> +                                    .grey),
missing trailing comma

2021-04-06 07:50 UTC, imtoori commented on packages/stream_chat_flutter/lib/src/message_input.dart
> +    BuildContext context, Member member);
missing trailing comma

2021-04-06 08:00 UTC, xsahil03x commented
@imtoori yes looks fine to me 👍🏼

2021-04-06 11:23 UTC, imtoori requested changes
missing docs and also, can you rename the default_mention_tile.dart file to mention_tile.dart?

2021-04-06 11:23 UTC, imtoori commented on packages/stream_chat_flutter/lib/src/default_mention_tile.dart
> +import 'package:flutter/material.dart';
missing docs in the whole class

2021-04-06 11:23 UTC, imtoori commented on packages/stream_chat_flutter/lib/src/message_input.dart
> +typedef MentionTileBuilder = Widget Function(
missing docs

2021-04-06 12:27 UTC, imtoori approved these changes
LGTM

2021-04-06 12:28 UTC, merged