Localization: Support for Spanish
GetStream/stream-chat-flutter pull request #592
Opened 2021-07-29 19:24 UTC by sachaarbonel

- Support for Spanish
- Fix some typos in French

2021-07-30 08:39 UTC, JcMinarro requested changes

2021-07-30 08:39 UTC, JcMinarro commented on packages/stream_chat_localizations/lib/src/stream_chat_localizations_es.dart
> +  String get launchUrlError => 'No se puede lanzar la url';
```suggestion
  String get launchUrlError => 'No se pudo abrir la url';
```

2021-07-30 08:39 UTC, JcMinarro commented on packages/stream_chat_localizations/lib/src/stream_chat_localizations_es.dart
> +  String get retryLabel => 'Inténtalo de nuevo';
```suggestion
  String get retryLabel => 'Inténtelo de nuevo';
```

2021-07-30 08:39 UTC, JcMinarro commented on packages/stream_chat_localizations/lib/src/stream_chat_localizations_es.dart
> +      '$count Respuestas al hilo de discusión';
```suggestion
      '$count respuestas al hilo de discusión';
```

2021-07-30 08:39 UTC, JcMinarro commented on packages/stream_chat_localizations/lib/src/stream_chat_localizations_es.dart
> +    if (replyCount == 1) return '1 Respuesta';
```suggestion
    if (replyCount == 1) return '1 respuesta';
```

2021-07-30 08:39 UTC, JcMinarro commented on packages/stream_chat_localizations/lib/src/stream_chat_localizations_es.dart
> +    return '$replyCount Respuestas';
```suggestion
    return '$replyCount respuestas';
```

2021-07-30 08:39 UTC, JcMinarro commented on packages/stream_chat_localizations/lib/src/stream_chat_localizations_es.dart
> +  String get loadingMessagesError => 'Mensajes de error de carga';
```suggestion
  String get loadingMessagesError => 'Hubo un error mientras se cargaba el mensaje';
```

2021-07-30 08:39 UTC, JcMinarro commented on packages/stream_chat_localizations/lib/src/stream_chat_localizations_es.dart
> +  String get instantCommandsLabel => 'Mandos instantáneos';
```suggestion
  String get instantCommandsLabel => 'Comandos instantáneos';
```

2021-07-30 08:39 UTC, JcMinarro commented on packages/stream_chat_localizations/lib/src/stream_chat_localizations_es.dart
> +    return 'Enviar de vuelta';
```suggestion
    return 'Reenviar';
```

2021-07-30 08:39 UTC, JcMinarro commented on packages/stream_chat_localizations/lib/src/stream_chat_localizations_es.dart
> +      'Enviado ${_getDay(date)} a ${Jiffy(time.toLocal()).format('HH:mm')}';
```suggestion
      'Enviado el ${_getDay(date)} a las ${Jiffy(time.toLocal()).format('HH:mm')}';
```

2021-07-30 08:39 UTC, JcMinarro commented on packages/stream_chat_localizations/lib/src/stream_chat_localizations_es.dart
> +  String get channelIsMutedText => 'El canal está cortado';
```suggestion
  String get channelIsMutedText => 'El canal está silenciado';
```

2021-07-30 08:39 UTC, JcMinarro commented on packages/stream_chat_localizations/lib/src/stream_chat_localizations_es.dart
> +  String get startAChatLabel => 'Iniciar una discusión';
```suggestion
  String get startAChatLabel => 'Iniciar una conversación';
```

2021-07-30 08:39 UTC, JcMinarro commented on packages/stream_chat_localizations/lib/src/stream_chat_localizations_es.dart
> +  String get searchingForNetworkText => 'Búsqueda en la red';
```suggestion
  String get searchingForNetworkText => 'Buscando red';
```

2021-07-30 08:39 UTC, JcMinarro commented on packages/stream_chat_localizations/lib/src/stream_chat_localizations_es.dart
> +  String get tryAgainLabel => 'Inténtalo de nuevo';
```suggestion
  String get tryAgainLabel => 'Inténtelo de nuevo';
```

2021-07-30 08:39 UTC, JcMinarro commented on packages/stream_chat_localizations/lib/src/stream_chat_localizations_es.dart
> +    if (count == 1) return '1 Membre';
```suggestion
    if (count == 1) return '1 miembro';
```

2021-07-30 08:39 UTC, JcMinarro commented on packages/stream_chat_localizations/lib/src/stream_chat_localizations_es.dart
> +    return '$count Membres';
```suggestion
    return '$count miembros';
```

2021-07-30 08:39 UTC, JcMinarro commented on packages/stream_chat_localizations/lib/src/stream_chat_localizations_es.dart
> +  String get leaveGroupLabel => 'Dejar el Grupo';
```suggestion
  String get leaveGroupLabel => 'Salir del Grupo';
```

2021-07-30 08:39 UTC, JcMinarro commented on packages/stream_chat_localizations/lib/src/stream_chat_localizations_es.dart
> +  String get leaveLabel => 'DEJAR';
```suggestion
  String get leaveLabel => 'SALIR';
```

2021-07-30 08:39 UTC, JcMinarro commented on packages/stream_chat_localizations/lib/src/stream_chat_localizations_es.dart
> +  String get leaveConversationLabel => 'Dejar la conversación';
```suggestion
  String get leaveConversationLabel => 'Salir de la conversación';
```

2021-07-30 08:39 UTC, JcMinarro commented on packages/stream_chat_localizations/lib/src/stream_chat_localizations_es.dart
> +      '¿Estás seguro de que quieres dejar esta conversación?';
```suggestion
      '¿Estás seguro de que quiere salir de esta conversación?';
```

2021-07-30 08:43 UTC, xsahil03x commented
Nice try @sachaarbonel

2021-07-30 08:56 UTC, imtoori requested changes
this is great
just a couple of things: 
- missing column
- can you add the Spanish support to the package readme and the guide on docusaurus as well?

2021-07-30 08:56 UTC, imtoori commented on packages/stream_chat_localizations/lib/src/stream_chat_localizations.dart
> +const kStreamChatSupportedLanguages = {'en', 'hi', 'fr', 'it', 'es'};
missing column

2021-07-30 08:57 UTC, JcMinarro submitted a review, later dismissed
Spanish translations are good now ;)

2021-07-30 09:00 UTC, xsahil03x commented
> Spanish translations are good now ;)

Thanks @JcMinarro for a great review 😄

2021-08-02 14:33 UTC, JcMinarro approved these changes

2021-08-04 20:02 UTC, xsahil03x approved these changes
LGTM

2021-08-06 10:30 UTC, merged