Understanding filters
GetStream/stream-chat-flutter pull request #615
Opened 2021-08-09 11:10 UTC by deven98

2021-08-11 12:26 UTC, funwithflutter requested changes

2021-08-11 12:26 UTC, funwithflutter commented on docusaurus/docs/Flutter/guides/understanding_filters.mdx
> +final filter = Filter.or([
Should this be `Filter` or `FilterOperator`. The title says FilterOperator.or

2021-08-11 12:26 UTC, funwithflutter commented on docusaurus/docs/Flutter/guides/understanding_filters.mdx
> +final filter = Filter.and([
Should this be `Filter` or `FilterOperator`. The title says FilterOperator.and

2021-08-11 12:26 UTC, funwithflutter commented on docusaurus/docs/Flutter/guides/understanding_filters.mdx
> +final filter = Filter.nor([
Should this be `Filter` or `FilterOperator`. The title says FilterOperator.nor

2021-08-11 12:26 UTC, funwithflutter commented on docusaurus/docs/Flutter/guides/understanding_filters.mdx
> +Matches values by performing text search with the specified value.
```suggestion
The 'query' filter matches values by performing text search with the specified value.
```

2021-08-11 12:26 UTC, funwithflutter commented on docusaurus/docs/Flutter/guides/understanding_filters.mdx
> +Matches values with the specified prefix.
```suggestion
The 'autoComplete' filter matches values with the specified prefix.
```

2021-08-11 12:26 UTC, funwithflutter commented on docusaurus/docs/Flutter/guides/understanding_filters.mdx
> +Matches values that exist/don't exist based on the specified boolean value.
```suggestion
The 'exists' filter matches values that exist, or don't exist, based on the specified boolean value.
```

2021-08-13 06:07 UTC, xsahil03x approved these changes
LGTM

2021-08-13 06:34 UTC, merged