feat: slow mode
GetStream/stream-chat-flutter pull request #626
Opened 2021-08-16 08:25 UTC by deven98

Adds slow mode

2021-08-18 12:01 UTC, deven98 commented on packages/stream_chat/lib/src/client/channel.dart
> +  ///
```suggestion
  /// Stores time at which cooldown was started
```

2021-08-18 12:16 UTC, imtoori commented
@deven98 I think it's possible to add a couple of tests, especially in the llc

2021-08-20 12:39 UTC, sachaarbonel requested changes

2021-08-20 12:39 UTC, sachaarbonel commented on packages/stream_chat_localizations/lib/src/stream_chat_localizations_ko.dart
> +  String get slowModeOnLabel => '느린 모드 켜짐';
```suggestion
  String get slowModeOnLabel => '슬로모드온 입니다.';
```
@EricSSartorius thoughts?

2021-08-20 12:39 UTC, sachaarbonel commented on packages/stream_chat_localizations/lib/src/stream_chat_localizations_ja.dart
> +  String get slowModeOnLabel => 'スローモードオン';
LGTM. @EricSSartorius ?

2021-08-20 15:06 UTC, EricSSartorius commented on packages/stream_chat_localizations/lib/src/stream_chat_localizations_ja.dart
> +  String get slowModeOnLabel => 'スローモードオン';
yeah that works

2021-08-20 15:07 UTC, EricSSartorius commented on packages/stream_chat_localizations/lib/src/stream_chat_localizations_ko.dart
> +  String get slowModeOnLabel => '느린 모드 켜짐';
슬로모드 켜짐 Might be best here

2021-08-20 15:12 UTC, imtoori commented on packages/stream_chat_localizations/lib/src/stream_chat_localizations_ko.dart
> +  String get slowModeOnLabel => '느린 모드 켜짐';
```suggestion
  String get slowModeOnLabel => '슬로모드 켜짐';
```

2021-08-23 07:57 UTC, imtoori approved these changes
LGTM

2021-08-23 07:58 UTC, merged